spring:
  config:
    activate:
      on-profile: test
    import:
      - application-jpa-test.yml
      - application-exposed-test.yml
  batch:
    job:
      name: ${job.name:NONE}
  kafka:
    consumer:
      bootstrap-servers: localhost:9092

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
