spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;INIT=CREATE SCHEMA IF NOT EXISTS KOTLIN_STUDY;
    username: sa
    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
#      springframework: debug

