spring:
  config:
    import:
      - application-jpa.yml
  batch:
    job:
      name: ${job.name:NONE}
logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml
