spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;INIT=CREATE SCHEMA IF NOT EXISTS KOTLIN_STUDY;
    username: sa
    password:
  exposed:
    show-sql: true
    generate-ddl: true

logging:
  level:
    Exposed: debug

